### ISSUE TITLE
YML support

### ISSUE THREAD

**Issue by madhead** [Heapy/heapy-properties-gradle-plugin#1]
![image](https://user-images.githubusercontent.com/577360/93531909-a803bc00-f948-11ea-8c8b-5ca3403f69e9.png)

**Comment by IRus** [comment]
Do you have an usecase for yml+gradle configuration?

**Comment by madhead** [comment]
Actually, no. I don't have a lot of usecases for `gradle.properties` either, TBH.

**Comment by IRus** [comment]
How to access `property.foo.bar` from Gradle? Looks like there are no pretty way: `project.ext["property.foo.bar"]`. I was thinking of passing `KType` to plugin, and then pass mapped value back. Then using yml will make sense, or even try to use kotlin scripting.

**Comment by madhead** [comment]
>project.ext["property.foo.bar"]

It seems to be the only way, yes.

**Comment by IRus** [comment]
Less is more, no plans to implement yml support
